### ISSUE TITLE
month is -1 in filename format

### ISSUE THREAD

**Issue by caseyg** [cmenscher/kindleHighlightLiberator#1]
Exported on February 25th, 2014, but date is output as 2014-1-25, which I read as January. (Correct should be 2014-2-25?)

![screenshot 2014-02-25 13 54 44](https://f.cloud.github.com/assets/462020/2261401/792c1500-9e4e-11e3-9032-342f3ac03289.png)

p.s. thanks for this!!!

**Comment by cmenscher** [comment]
Oops!  Thanks for noticing. Fixed now.
